<?php if (substr_count($_SERVER['HTTP_ACCEPT_ENCODING'], 'gzip')) ob_start("ob_gzhandler"); else ob_start(); ?>
<?php
date_default_timezone_set("Asia/Kolkata");
?>
<!DOCTYPE html>
<html>
<head>
<title>Otaku ~ Sitemap</title><meta name="viewport" content="width=device-width, initial-scale=1" /><meta name="author" content="Otaku"><meta name="description" content="Site Map ~ Otaku"><link rel="icon" type="image/x-icon" href="css/favicon.ico" />
<link rel="shortcut icon" href="css/favicon.ico" type="image/x-icon" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<style type="text/css">
body {
background-color: #DDD;
font: normal 80%  "Trebuchet MS", "Helvetica", sans-serif;
margin:0;
text-align:center;
}
#cont{
margin:auto;
width:800px;
text-align:left;
}
a:link,a:visited {
color: #0180AF;
text-decoration: underline;
}
a:hover {
color: #666;
}
h1 {
background-color:#fff;
padding:20px;
color:#00AEEF;
text-align:left;
font-size:32px;
margin:0px;
}
h3 {
font-size:12px;
background-color:#B8DCE9;
margin:0px;
padding:10px;
}
h3 a {
float:right;
font-weight:normal;
display:block;
}
th {
text-align:center;
background-color:#00AEEF;
color:#fff;
padding:4px;
font-weight:normal;
font-size:12px;
}
td {
font-size:12px;
padding:3px;
text-align:left;
}
tr {background: #fff}
tr:nth-child(odd) {background: #f0f0f0}
#footer {
background-color:#B8DCE9;
padding:10px;
}
.pager,.pager a {
background-color:#00AEEF;
color:#fff;
padding:3px;
}
.lhead {
background-color:#fff;
padding:3px;
font-weight:bold;
font-size:16px;
}
.lpart {
background-color:#f0f0f0;
padding:0px;
}
.lpage {
font:normal 12px verdana;
}
.lcount {
background-color:#00AEEF;
color:#fff;
padding:2px;
margin:2px;
font:bold 12px verdana;
}
a.aemphasis {
color:#009;
font-weight:bold;
}
</style>

</head>
<body>
<div id="cont">
<h1>HTML Site Map</h1>
<h3><a href="http://www.otakud.in">Homepage</a>
Last updated: <?php echo date('r') ?>
</h3>


<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr valign="top">
<td class="lpart" colspan="100"><div class="lhead">/
<span class="lcount">10 pages</span></div>

<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr><td class="lpage"><a href="http://www.otakud.in/" title="Otaku">Otaku</a></td></tr>
<tr><td class="lpage"><a href="http://www.otakud.in/index.php" title="Otaku">Otaku</a></td></tr>
<tr><td class="lpage"><a href="http://www.otakud.in/about.php" title="Otaku ~ about us">Otaku ~ about us</a></td></tr>
<tr><td class="lpage"><a href="http://www.otakud.in/pricerangechart.php" title="Otaku ~ price range chart">Otaku ~ price range chart</a></td></tr>
<tr><td class="lpage"><a href="http://www.otakud.in/contact.php" title="Otaku ~ contactus">Otaku ~ contactus</a></td></tr>
<tr><td class="lpage"><a href="http://www.otakud.in/web.php" title="Otaku ~ webdesigning">Otaku ~ webdesigning</a></td></tr>
<tr><td class="lpage"><a href="http://www.otakud.in/domain.php" title="Otaku ~ domains">Otaku ~ domains</a></td></tr>
<tr><td class="lpage"><a href="http://www.otakud.in/host.php" title="Otaku ~ hosting">Otaku ~ hosting</a></td></tr>
<tr><td class="lpage"><a href="http://www.otakud.in/email.php" title="Otaku ~ emails">Otaku ~ emails</a></td></tr>
<tr><td class="lpage"><a href="http://www.otakud.in/ssl.php" title="Otaku ~ SSL">Otaku ~ SSL</a></td></tr>
</table>
</td>
</tr>

<tr valign="top">
<td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td class="lpart" colspan="99"><div class="lhead">ca/
<span class="lcount">1 pages</span></div>

<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr><td class="lpage"><a href="http://www.otakud.in/ca/index.php" title="Otaku ~ Client Area">Otaku ~ Client Area</a></td></tr>
</table>
</td>
</tr>

</table>
<div id="footer">
Page generated by Otaku - <a target="_blank" href="sitemap.php">Sitemap</a>
|
Copyright &copy; 2015-<?php echo date('Y') ?>

</div>
</div>
</body>
</html>
